### ISSUE TITLE
Not showing all nodes

### ISSUE THREAD

**Issue by dinabogdan** [tchiotludo/kafkahq#100]
Hi,

I'm facing the following issue that even if I've configured the bootstrap.servers property with a list including all Kafka nodes, in the GUI sometimes I see only two of the nodes and after restarting the other node that I've not seen previously.

I should mention that KafkaHQ is deployed on the same machine with the node that is not shown in the list.

My application.yaml file is the following one:
kafkahq:
  connections:
    cluster-1:
      properties:
        bootstrap.servers: "172.16.207.131:9092,172.16.207.135:9092,172.16.207.191:9092"
      schema-registry:
        url: "http://172.16.207.135:8081"

  # Topic list display options (optional)
  topic:
    page-size: 25 # number of topics per page (default : 25)
    default-view: HIDE_INTERNAL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"

  # Topic display data options (optional)
  topic-data:
    sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
    size: 50 # max record per page (default: 50)
    poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.

  # Schama list display options (optional)
  schema:
    page-size: 25 # number of schemas per page (default : 25)

  # Auth & Roles (optional)
  security:
    default-roles: # Roles available for all the user even unlogged user
      - topic/read
      - topic/insert
      - topic/delete
      - topic/config/update
      - node/read
      - node/config/update
      - topic/data/read
      - topic/data/insert
      - topic/data/delete
      - group/read
      - group/delete
      - group/offsets/update
      - registry/read
      - registry/insert
      - registry/update
      - registry/delete
      - registry/version/delete
      - connect/read
      - connect/insert
      - connect/update
      - connect/delete
      - connect/state/update

    # Basic auth configuration
    basic-auth:
      user: # Username
        password: pass # Password in sha256
        roles: # Role for current users
          - topic/read
          - group/read
          - group/delete

**Comment by dinabogdan** [comment]
The problem occurred because the properties: listeners & advertised.listeners were not set for the specific node. But it is strange because at a certain point in time KafkaHQ showed me only this specific node without the other two nodes.

**Comment by tchiotludo** [comment]
Hello, 
sorry for the late response. 

I think it's normal as I understand connection protocol for kafka, I will pick 1 random server on the list. 
- If it pick a misconfigured node, kafka cli will only see this one
- If it pick one of 2 others one, kafka cli will only see 2 nodes and not the misconfigured.
