### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by HungUnicorn** [tchiotludo/kafkahq#101]
I found kafkahq could outperform kafka-manager more, if LDAP support is enabled as kafka-manager does

https://github.com/yahoo/kafka-manager#authenticating-a-user-with-ldap

Is the LDAP support already available via configuration and without any code change? as the micronaut document written here
https://micronaut-projects.github.io/micronaut-security/latest/guide/#ldap

**Comment by tchiotludo** [comment]
there is only one issue, ldap global identification is available with micronaut, but I need to develop a function to allow to map kafkahq role with ldap authentificaton (using this : https://micronaut-projects.github.io/micronaut-security/latest/guide/#extending). 
But I need to do it for users & groups to be easily used within enterprise. 

As a lot of people is waiting for this, I will put it on first next features

**Comment by zthulj** [comment]
Hey @tchiotludo, are you working on this ? If not, I would like to give it a try.

**Comment by tchiotludo** [comment]
Hey @zthulj, one people is working on it right now, bit since micronaut 1.2.0, there is ouath 2.0 support, if you search something. Can be cool for gsuite and others ?

What do you think ?

**Comment by zthulj** [comment]
Yes, I think it's a good idea. I would love to see kafkahq work with my keycloak. A dedicated issue could be usefull though

**Comment by tchiotludo** [comment]
done in #142 :D
