### ISSUE TITLE
optional used as type for parameter - warning by intelij

### ISSUE THREAD

**Issue by HungUnicorn** [tchiotludo/kafkahq#102]
Should we perhaps use `optional` only for return type?

the warning is from here for example:
https://github.com/tchiotludo/kafkahq/blob/dev/src/main/java/org/kafkahq/controllers/TopicController.java#L73

**Comment by tchiotludo** [comment]
I've seen this but since it was the only way to deal with optional query string with micronaut

Don't any other solution as I know

**Comment by HungUnicorn** [comment]
hmm, in springboot optional query string is the parameter without `@required`
