### ISSUE TITLE
Connector definition update

### ISSUE THREAD

**Issue by leosilvadev** [tchiotludo/kafkahq#107]
Hello Guys!
Sorry if this is a too simple question.
We are using kafkahq here but still checking some features (so far everything works great for us), but we just faced one thing now, we could not manage to update the definition of a connector. I tried to pause and see weather this becomes possible but nothing. Now I am looking at the code to understand it better but I would also like to check with you about that. Is that available now? If yes, in which circumstances?
I am logged with all the permissions set

**Comment by leosilvadev** [comment]
<img width="1416" alt="Screen Shot 2019-08-26 at 17 27 50" src="https://user-images.githubusercontent.com/5465808/63702341-14d08380-c827-11e9-8376-7ffa36dd53a5.png">

**Comment by tchiotludo** [comment]
Hello, 
As i know, it's working but I don't have use a lot by myself. 
I rely on kafka connect api to have the list of the configuration on edit page. 

Maybe it's a custom connector ? That don't expose configuration on kafka connect api ? 
I use internaly this api to have configuration option : https://docs.confluent.io/current/connect/references/restapi.html#put--connector-plugins-(string-name)-config-validate

**Comment by leosilvadev** [comment]
@tchiotludo thanks for the fast reply!
Yes, it is a custom connector. Will check it out and update in here, thank you!

**Comment by tchiotludo** [comment]
If the api don't return anything, tell me, I will block update for this kind on connector

**Comment by leosilvadev** [comment]
Hello @tchiotludo ! I checked the link and did the call to the API directly, looks like all the definitions are coming in the response

**Comment by tchiotludo** [comment]
Is it possible to have an export from the api request ? (anonymized if needed) ?

**Comment by leosilvadev** [comment]
Okay, maybe I got the point. Debugging here I noticed that at the `this.connectRepository.getPlugin(cluster, definition.getShortClassName())` call (ConnectController line 201) it returns empty, since the `definition.getShortClassName()` is returning the full path of the class

**Comment by leosilvadev** [comment]
But calling this function with the class name (not the full path) it works

**Comment by leosilvadev** [comment]
Checking the connector api I also noticed even when the class.name in the body is not the full path it returns the expected plugin (that is probably why when I changed the shortname method to return just the class name it worked)

**Comment by leosilvadev** [comment]
I got the point. The issue here is because the method ConnectDefinition#getShortClassName returns the full class path and ConnectPlugin#getShortClassName returns just the class name, so it does not match at ConnectRepository#getPlugin filter

**Comment by leosilvadev** [comment]
This fixed the issue, do you think it makes sense? See a breaking point somewhere else?

https://github.com/tchiotludo/kafkahq/pull/108

**Comment by tchiotludo** [comment]
I've merged on dev branch, you can make a try.
I don't see any issue on my side.
Let me know if it works well :smile:

**Comment by leosilvadev** [comment]
@tchiotludo worked like a charm!
Thanks for the help! Btw, I would love to contribute more with the tool. If there is anything you have in mind for new features I would be happy to talk! I am also going to keep my eyes on the tickets opened.
[]'s
