### ISSUE TITLE
Missing topic from the topic list

### ISSUE THREAD

**Issue by ebrard** [tchiotludo/kafkahq#113]
I've created a topic with kafkahq directly with a name of 49 characters and it doesn't show up back in the list of topic.

**Comment by tchiotludo** [comment]
do you see the topic with `kafkacat` or `kafka-topics.sh` command ?

**Comment by ebrard** [comment]
Yes, I've checked that it was really created :)

**Comment by tchiotludo** [comment]
Is it possible to give me the topic name to test on my side ?

**Comment by ebrard** [comment]
I tried with a different name of the same length and it works properly. Now this topic is part of a set of about ~200 topics with the same prefix (something.something1, something.something2...). When I try to search for an exact match on any of them (i.e. something.something2), I get no result even when they are actually listed. When I try to search for a topic with no specific pattern, then it works.

I suspect this is because of the topic pagination, would that be possible ?

**Comment by ebrard** [comment]
Ok I ran this test. I created quite a few topics:
```
counter=0; until [ $counter -gt 201 ]; do kafka-topics --zookeeper zookeeper:2181 --create --topic test.oftopic_${counter} --partitions 1 --replication-factor 1; ((counter++)); done

counter=6; until [ $counter -gt 50 ]; do kafka-topics --zookeeper zookeeper:2181 --create --topic analytics-pipeline.oftopic_${counter} --partitions 1 --replication-factor 1; ((counter++)); done
```

Then created `analytics-pipeline.zQuiteALongStringToMakeItNotWork` from the tool, and looked for it with the search function, and that did not work. Browsing through the pages I can find it.

So it's probably an issue with the search function.

**Comment by tchiotludo** [comment]
Just add the biggest bug fix in the world :laughing:
