### ISSUE TITLE
Link error to schema registry with id greater than 1,000 

### ISSUE THREAD

**Issue by sebco59** [tchiotludo/kafkahq#114]
Hi,
In the data view of a topic, you can access to the detail of an avro file. My avro id is "100,007"

<img width="327" alt="Capture d’écran 2019-09-10 à 14 51 43" src="https://user-images.githubusercontent.com/40773986/64615345-a53bc600-d3da-11e9-9c2e-95b123d7e49e.png">
The link is http://kafkahq/my-cluster/schema/id/100,007 with the comma and it gives me an error:

> Failed to convert argument [id] for value [100,007] due to: For input string: "100,007"
> io.micronaut.core.convert.exceptions.ConversionErrorException: Failed to convert argument  [id] for value [100,007] due to: For input string: "100,007"
> 	at >io.micronaut.web.router.AbstractRouteMatch.lambda$resolveValueOrError$4(AbstractRouteMatch.java:353)
>	at java.base/java.util.Optional.map(Optional.java:265)
>	at io.micronaut.web.router.AbstractRouteMatch.resolveValueOrError(AbstractRouteMatch.java:352)
>	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:290)

If I remote the comma, everything is ok.
Thx
My version: kafkahq:dev in k8s with Confluent Cloud

**Comment by tchiotludo** [comment]
Just fix, thanks for the report
