### ISSUE TITLE
Message display: long lines in payload make display area very broad, no horizontal scrollbar

### ISSUE THREAD

**Issue by dl1ely** [tchiotludo/kafkahq#12]
First, thanks for providing this tool, it is amazing!

We are sending long JWT tokens along in our Kafka message payloads. When viewing data, this leads to a very broad area for displaying the payload, but there is no horizontal scrollbar.

Even worse, that makes the table on top of the payload for key, partiton, offset and headers also very broad. As the width is evenly distributed between the 4 columns, only the first one (key) is visible, the other 3 are outside the visible area on the right.

Horizontal scrolling is possible by using mouse shortcuts (press middle mouse button and move left or right), but this is very sensitive and still very inconvenient for looking at headers, for example. 

I understand that finding a nice solution for displaying very long lines is hard, but the width of the table holding key, partition, offset and headers should be determined by the viewport width, not the width of the payload area below it.

Browser is Firefox 64 on Windows 10.

**Comment by tchiotludo** [comment]
ok got it, the bug is on firefox only as I know.

Will handle it asap
