### ISSUE TITLE
[new features] Add compression information on message

### ISSUE THREAD

**Issue by apellegr06** [tchiotludo/kafkahq#122]
Hello,

It could be good to have the compression information on the header part of each message.

**Comment by tchiotludo** [comment]
I will look at but I think the Kafka API don't let me know this. 
I can only know at the topic level, but As I know, the producer can override the compression per message and kafkaAPI don't return the information

**Comment by zthulj** [comment]
Hey,
Compression is not a message linked information, but a "batch" information.
Messages are sent by producer as "batch" and they are also read as "batch" from the consumer. (Even 1 message is a batch of 1 message)

We can see this behavior here :
https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java

So, compression is handled by the internal Kafka client classes and the information is not provided.
TBH I think it's not possible to display this one.

**Comment by tchiotludo** [comment]
closing since it's not possible with actual Kafka Api
