### ISSUE TITLE
Replications factor

### ISSUE THREAD

**Issue by mt3593** [tchiotludo/kafkahq#124]
I'm a bit confused with the replication factor given back in the topic page.

Looking via the kafka tools I get:

```bash
Topic:xxx	PartitionCount:9	ReplicationFactor:2	Configs:retention.ms=-1
	Topic: xxx	Partition: 0	Leader: 2	Replicas: 2,1	Isr: 2,1
	Topic: xxx	Partition: 1	Leader: 0	Replicas: 0,2	Isr: 0,2
	Topic: xxx	Partition: 2	Leader: 1	Replicas: 1,0	Isr: 1,0
	Topic: xxx	Partition: 3	Leader: 2	Replicas: 2,0	Isr: 2,0
	Topic: xxx	Partition: 4	Leader: 0	Replicas: 0,1	Isr: 0,1
	Topic: xxx	Partition: 5	Leader: 1	Replicas: 1,2	Isr: 1,2
	Topic: xxx	Partition: 6	Leader: 2	Replicas: 2,1	Isr: 2,1
	Topic: xxx	Partition: 7	Leader: 0	Replicas: 0,2	Isr: 0,2
	Topic: xxx	Partition: 8	Leader: 1	Replicas: 1,0	Isr: 1,0

```

Which shows I have 2 replicas for each of the partitions.

But when I look on kafka-hq topic page I see a replications factor of 6. Could be a bug or my understanding of what the data is showing.

The cluster is setup with 3 kafka nodes and the topic as you can see has 9 partitions.

**Comment by tchiotludo** [comment]
Can you provide me the same visualization on details page please ? 
It's on url `/{{cluster}}/topic/{{topic}}/partitions`. 

I will have the same view than kafka tools, but It can be a bug as I look at the code.

In sync replicas can be affected by the same bug, nice I you can give the values on topic list page .

**Comment by mt3593** [comment]
Hey @tchiotludo 

Very speedy on the reply! 

So for that page I get:
```
Id	Leader	Replicas	Offsets	Size	
0	2	2 1	0 ⤑ 792	792 - 331.5 ko	
1	0	0 2	0 ⤑ 790	790 - 332.4 ko	
2	1	1 0	0 ⤑ 780	780 - 329.4 ko	
3	2	2 0	0 ⤑ 746	746 - 317.2 ko	
4	0	0 1	0 ⤑ 806	806 - 338.4 ko	
5	1	1 2	0 ⤑ 816	816 - 342.4 ko	
6	2	2 1	0 ⤑ 826	826 - 349.4 ko	
7	0	0 2	0 ⤑ 760	760 - 322.6 ko	
8	1	1 0	0 ⤑ 818	818 - 346.3 ko	
```

Which is the same as the one I get from the command line so that looks right.

**Comment by mt3593** [comment]
Yes the replications in sync is also 6, so the bug does affect this too.

**Comment by tchiotludo** [comment]
Thanks for the report !
It's fixed on dev image
