### ISSUE TITLE
[feature] Add acls visualization

### ISSUE THREAD

**Issue by zthulj** [tchiotludo/kafkahq#131]
Hi,

I've started to work a little on this feature cause I wanted it for my cluster. Before to go further, as you made a survey with it, I wanted to know if you're okay with this new feature, and to be sure we agree on the good design on it.

The goal is to add a tab in a topic view, called "Acls".
This tab will be divided in two parts : 

One is to display user acls and the other to display groups acls. In fact, to connect to a topic, a producer need only to have the user correct but a consumer can be limited to one or more groups. 

As I imagine this, I would make it simple, like two tables. One with "user, permission, hosts" and the other with "group, permission, hosts".

I also want to add a new role called "acls/read", because that's a thing we may want to keep for an admin account.

For now, I don't think it's "usefull" to add the modify acls, to start I guess just the visualization is good. 

What do you think ?

**Comment by tchiotludo** [comment]
Hello, 

I've no objection on acl on KafkaHQ, and I will be a nice addition to it.
To be honest, it was on my roadmap but I don't have the time for now, so PR will be really appreciate.

For the visualization, I will have opt to a list of users in a table and a detail page with tabs for group and user right. 

This one will be transform into a form later when the edition will be available (you know like schema registry page)

The edit part will be a nice addition also, but starting with visualization is already nice.

Does this make sense for you ?

**Comment by zthulj** [comment]
To be sure, I made a quick model.

As I understand, we could have a new view called "users" on the left menu, linking to a list of users : 

![image](https://user-images.githubusercontent.com/43185161/66871342-bbbdda00-efa3-11e9-84b2-306b6146db87.png)

Then, when we click on the detail link, we go to a dedicated page : 
![image](https://user-images.githubusercontent.com/43185161/66871387-d7c17b80-efa3-11e9-8ca2-81ee6b59a4ec.png)

And of course, we may add a tab in the topic visualization to quickly see who has permissions on the topic :
![image](https://user-images.githubusercontent.com/43185161/66871439-f32c8680-efa3-11e9-8a47-941339506f52.png)

Later, the detail page could be transformed into a form.
Did I get it ?

**Comment by tchiotludo** [comment]
Exactly ! 
Just try to condensed the view on detailed page : one rows per topic (or groups) / host and maybe used bootstrap label to display acls inline.
Later, we will add a button on this line to edit the whole part on a dedicated form  

Good catch to tab on topic page, maybe also on consumer page :angel: 
On these page, I think the same expanded view could be fine (group per user / host this time).

Also could you named it "ACLS" please. 

Thanks a lot :+1:
