### ISSUE TITLE
Provide (optional) schema Id to produce record

### ISSUE THREAD

**Issue by MBOIX** [tchiotludo/kafkahq#138]
In order to produce a record which is attached to an Avro schema, i need to specify the id of schema Id in `produce` view form.

**Comment by tchiotludo** [comment]
Already in my head RoadMap. 

Need a little bit of design since on the produce page, you will have to put your your message in JSON format (or else) and serialized to avro before producing on the topic.
 
Maybe a good issue for hacktoberfest with your friend of  @Zenika :smile:
