### ISSUE TITLE
Error: Unable to access jarfile /app/kafkahq.jar

### ISSUE THREAD

**Issue by abhishekjalan87** [tchiotludo/kafkahq#140]
After deploying the docker container I am getting below error:

Error: Unable to access jarfile /app/kafkahq.jar

**Comment by tchiotludo** [comment]
what image do you use ? 
can you provide the docker run command, docker-compose file, or kubernetes file ?

**Comment by abhishekjalan87** [comment]
kafkahq git:(master) docker build -t ajalan/kafkahq .                                                                        
Sending build context to Docker daemon  960.5kB
Step 1/6 : FROM openjdk:11-slim
11-slim: Pulling from library/openjdk
8d691f585fa8: Pull complete 
3da6fe7ff2ef: Pull complete 
e22147996cc0: Pull complete 
ebc78a5f677c: Pull complete 
Digest: sha256:9f4a87a6c3c99db1f56e58403de4c61aae73e8efc5c6cea30c233080bfd3af9a
Status: Downloaded newer image for openjdk:11-slim
 ---> c41356b393a7
Step 2/6 : WORKDIR /app
 ---> Running in 805022947f03
Removing intermediate container 805022947f03
 ---> fd9cdcd13de3
Step 3/6 : COPY docker /
 ---> aa3359e30976
Step 4/6 : ENV MICRONAUT_CONFIG_FILES=/app/application.yml
 ---> Running in 90191b7b3121
Removing intermediate container 90191b7b3121
 ---> 6a5a6382c07b
Step 5/6 : ENTRYPOINT ["docker-entrypoint.sh"]
 ---> Running in 63d930aa483b
Removing intermediate container 63d930aa483b
 ---> 81bd730cc224
Step 6/6 : CMD ["./kafkahq"]
 ---> Running in 1379c6033f9b
Removing intermediate container 1379c6033f9b
 ---> 51457e6adaac
Successfully built 51457e6adaac
Successfully tagged ajalan/kafkahq:latest
➜  kafkahq git:(master) docker run -d \                 
    -p 8080:8080 \
    -v /tmp/application.yml:/app/application.yml \
    ajalan/kafkahq:latest
8d4075cabb38aa3139fcf4db623e597feb928ba48dd891aa61eebbacd6525527
➜  kafkahq git:(master) docker ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                     PORTS               NAMES
8d4075cabb38        ajalan/kafkahq:latest   "docker-entrypoint.s…"   4 seconds ago       Exited (1) 3 seconds ago                       sharp_williams
➜  kafkahq git:(master) docker logs 8d4075cabb38
Error: Unable to access jarfile /app/kafkahq.jar

**Comment by abhishekjalan87** [comment]
even I tried with dev branch also :(

**Comment by tchiotludo** [comment]
from the source (docker build cmd), it's normal, the jar is not in the source and you must build the jar before with `./gradlew shadowJar` but there is no need to build it, the docker image is working.

Can you give me the docker run who use with the dev branch that don't work ?

**Comment by abhishekjalan87** [comment]
so you mean first I need to build the jar before I run docker build -t atchiotludo/kafkahq . ?

**Comment by tchiotludo** [comment]
yes, but it's really weird that you can't use the docker image I provide ...
