### ISSUE TITLE
Bug on 0.10.0 : could not be established. Broker may not be available

### ISSUE THREAD

**Issue by apellegr06** [tchiotludo/kafkahq#146]
Hi,

On the last release (0.10.0) when there is one offline broker in the bootstrap I obtain an error :

 WARN  l-worker-1 o.a.k.c.NetworkClient      [Consumer clientId=consumer-472, groupId=KafkaHQ] Connection to node -1 (xxxxxx/yyyyyy:zzzz) could not be established. Broker may not be available.

If I remove the offline broker from the bootstrap it works fine.

**Comment by tchiotludo** [comment]
Hello, 

It's only a WARM in console ?
It doesn't affect KafkaHQ and the page are working ?

**Comment by apellegr06** [comment]
Hello,

It's a WARN in log file and it's blocking to access to the WEB interface.

**Comment by tchiotludo** [comment]
The error is displayed on KafkaHQ gui ? 
But the bug is on Kafka API, I can't handle it on my side

**Comment by apellegr06** [comment]
It's strange, I have added again the broken broker and now it's working !
