### ISSUE TITLE
docker-compose up failed

### ISSUE THREAD

**Issue by shishal** [tchiotludo/kafkahq#15]
I just tried _docker-compose up_ and it failed with following errro:

> Starting kafkahq_webpack_1 ... done
Starting kafkahq_kafkahq_1 ... done
Attaching to kafkahq_webpack_1, kafkahq_kafkahq_1
kafkahq_1  | 
kafkahq_1  | FAILURE: Build failed with an exception.
kafkahq_1  | 
kafkahq_1  | * Where:
kafkahq_1  | Build file '/app/build.gradle' line: 20
kafkahq_1  | 
kafkahq_1  | * What went wrong:
kafkahq_1  | Plugin [id: 'com.moowork.node', version: '1.2.0'] was not found in any of the following sources:
kafkahq_1  | 
kafkahq_1  | - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
kafkahq_1  | - Plugin Repositories (could not resolve plugin artifact 'com.moowork.node:com.moowork.node.gradle.plugin:1.2.0')
kafkahq_1  |   Searched in the following repositories:
kafkahq_1  |     Gradle Central Plugin Repository
kafkahq_1  | 
kafkahq_1  | * Try:
kafkahq_1  | Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
kafkahq_1  | 
kafkahq_1  | * Get more help at https://help.gradle.org
kafkahq_1  | 
kafkahq_1  | BUILD FAILED in 7s
kafkahq_kafkahq_1 exited with code 1

>

**Comment by tchiotludo** [comment]
I just add a new `docker-compose.yml` to preview KafkaHQ. 
The previous one was dev env docker-compose. 

It should be more clear like that I think
