### ISSUE TITLE
topic delete button should not be shown if current user has no rights

### ISSUE THREAD

**Issue by jorgheymans** [tchiotludo/kafkahq#151]
If the `topic/delete` role is not present for the current logged user, it does not make sense to render the topic delete buttons.

**Comment by jorgheymans** [comment]
a bit more information perhaps how this is occurring. In our config, there are no default roles, so anonymous users should not be able to do anything. So the `security -> default roles` section is empty. It turns out that the delete button is still present for anonymous users, but is correctly hidden once logged in.

**Comment by tchiotludo** [comment]
I've just try just now, I can't reproduce the bug. 
Are you talking about the topic list ? 
When I remove the role `topic/delete` role on the last dev version (with group based roles), the delete button is remove. 
Need more information on this one please :)

**Comment by jorgheymans** [comment]
Is the dev version published as a jar somewhere ? We don't run docker in our org here...

**Comment by tchiotludo** [comment]
You can find instruction to get the jar from the docker image from your laptop here : https://github.com/tchiotludo/kafkahq#development-environment
