### ISSUE TITLE
Big performance issue on 0.10.0

### ISSUE THREAD

**Issue by apellegr06** [tchiotludo/kafkahq#156]
Hi,

I have a big performance issue on the new release 0.10.0
If I compare to the previous one (0.9), to access to the first screen of the UI :
- In 0.9 : 5 seconds
- In 0.10 : 50 seconds

And so I can't use the new version it's impossible, to much waiting time.

For information, it's the really when I access to the topics list (I have more than 1500 topics)

**Comment by tchiotludo** [comment]
Can you provide me a log output after issuing this curl (replace localhost with your kafkahq url) :
```bash
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:8080/loggers/org.kafkahq
```
And try to load the topiclist page 
Feel free to remove sensitve data (topic & consumer group name).

**Comment by apellegr06** [comment]
it's too long to publish here, how can I send it to you ?

**Comment by tchiotludo** [comment]
tchiot.ludo@gmail.com thanks

**Comment by apellegr06** [comment]
It's done, have you receive ?

**Comment by tchiotludo** [comment]
receive, just hard to understand since all the topic are anodized, so hard to figure if there is some duplicate query to kafka api. 
First felling is that there is a lot of call to Describe Topics (env 6000) that is not normal with pagination ?

**Comment by apellegr06** [comment]
Do you need me to do more testing to help you investigate ?

**Comment by tchiotludo** [comment]
No it's ok, I can reproduce the bug on my side. 
Will need to dig to find a solution here

**Comment by tchiotludo** [comment]
Can you try with last dev version please ? 
Must be better than 0.10.0 and also better than 0.9.0 as I think

**Comment by apellegr06** [comment]
I can try with that, but I don't know how to build the dev version (I'm not  a Java dev, just an ops ;))

**Comment by tchiotludo** [comment]
Just added instruction on README : https://github.com/tchiotludo/kafkahq#early-dev-image

**Comment by apellegr06** [comment]
Thanks, but I obtain an error :

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not resolve io.confluent:kafka-schema-registry-client:5.3.+.
     Required by:
         project :
      > Failed to list versions for io.confluent:kafka-schema-registry-client.
         > Unable to load Maven meta-data from http://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/maven-metadata.xml.
            > Could not get resource 'http://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/maven-metadata.xml'.
               > Could not GET 'http://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/maven-metadata.xml'. Received status code 403 from server: Forbidden
   > Could not resolve io.confluent:kafka-avro-serializer:5.3.+.
     Required by:
         project :
      > Failed to list versions for io.confluent:kafka-avro-serializer.
         > Unable to load Maven meta-data from http://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/maven-metadata.xml.
            > Could not get resource 'http://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/maven-metadata.xml'.
               > Could not GET 'http://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/maven-metadata.xml'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 9s

**Comment by tchiotludo** [comment]
Weird that, the url http://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/maven-metadata.xml is working, seems to be a network issue on your side.
Use the docker method, it works well and no need to compile.

**Comment by tchiotludo** [comment]
release 0.11.0 include this improvement, no need to compile it anymore :)

**Comment by apellegr06** [comment]
Great release (0.11.0) ! Thank you so much for all improvement, it's a wonderfull tool !
