### ISSUE TITLE
static resource not loaded

### ISSUE THREAD

**Issue by shishal** [tchiotludo/kafkahq#16]
Started with command _java -jar kafkahq.jar prd_ .
Local server started but static resources like js,css did not loaded. PFA screenshot 
![screenshot from 2019-01-26 13-26-48](https://user-images.githubusercontent.com/6167159/51787228-894b2300-216f-11e9-88f4-d6879323236b.png)

**Comment by tchiotludo** [comment]
exact command is :  `java -jar kafkahq.jar prod`.
You have forgot the o on prod

**Comment by shishal** [comment]
Indeed. Sorry to bother.

**Comment by tchiotludo** [comment]
np :smile:
