### ISSUE TITLE
update micronaut version

### ISSUE THREAD

**Issue by jorgheymans** [tchiotludo/kafkahq#160]
Attempting to find a solution for #157 , i wanted to set `micronaut.session.http.cookie-max-age` but alas no luck because of a regression in micronaut https://github.com/micronaut-projects/micronaut-security/issues/73 . Updating to 1.2.6 should do the trick. I'ld raise a PR but unless i can build locally on windowsn there is no point because i would not even be able to test this.

**Comment by tchiotludo** [comment]
Not really sure that will help on this case but micronaut is updated on dev branch.
