### ISSUE TITLE
Topic page datepicker off by 1 day in UI

### ISSUE THREAD

**Issue by shishal** [tchiotludo/kafkahq#17]
Topic page datepicker off by 1 day in UI. Though when applied it take correct value.  Just in datepicker UI textbox it shows 1 day older than selected day.
![datetimepicker](https://user-images.githubusercontent.com/6167159/51793948-fdfe7b80-21c8-11e9-8991-5ff295d99a0e.png)

**Comment by tchiotludo** [comment]
What is your timezone ?
The picker convert automatically to UTC timezone since Kafka use timestamps (so utc time)

**Comment by shishal** [comment]
My Timezone is GMT+1.

**Comment by tchiotludo** [comment]
I'm on the same timezone, will have a look at it.

**Comment by tchiotludo** [comment]
Just because the timezone is converted to utc.
