### ISSUE TITLE
show trace in task status view

### ISSUE THREAD

**Issue by hoeggi** [tchiotludo/kafkahq#171]
When using Kafka Connect, would it be possible to also show the error message/stacktrace in the task detail view if a task is in a FAILED state?

**Comment by tchiotludo** [comment]
Thanks for the report :) 

I don't see I have the trace so easily available before :+1:

**Comment by dominics** [comment]
@tchiotludo Thanks for this feature! Much appreciated :)

**Comment by tchiotludo** [comment]
thanks :) 
it was easy :+1:
