### ISSUE TITLE
basic-auth & topics

### ISSUE THREAD

**Issue by pmpetit** [tchiotludo/kafkahq#173]
Hi, 
on the last version, (0.11.0), it looks like actions we can do when logged are not in the good order : 
i mean that, when i am not logged, i can delete drop topics and so on....
but when i am authenticated, i can not.

**Comment by tchiotludo** [comment]
Hello, 

Can you provide me the configuration you use please ? 
We have changed on lot of things on auth on this version : 

Here is an example : https://github.com/tchiotludo/kafkahq/blob/dev/application.example.yml#L146
There is also 2 default group, admin & reader to facilitate the configuration

**Comment by pmpetit** [comment]
Hello,
it is ok now with the application.example.yml
thx

**Comment by tchiotludo** [comment]
glad to know it :) 

don't forgot this one when you have some free time : https://github.com/tchiotludo/kafkahq/issues/161
