### ISSUE TITLE
update sink connector with registry

### ISSUE THREAD

**Issue by pmpetit** [tchiotludo/kafkahq#179]
Hi,
i have a sink connector that uses schema_registry : 
  "key.converter.schema.registry.url": "http://kafka-registry:8081"

i can see it in the json from kafkahq, "connect page"
When i go to config, in all the fields, i can not see the schema registry field.

When i update, then i face this error : 
020-01-09 07:43:42,911] ERROR Failed to start task check_refresh_time-0 (org.apache.kafka.connect.runtime.Worker) io.confluent.common.config.ConfigException: Missing required configuration "schema.registry.url" which has no default value.

**Comment by tchiotludo** [comment]
Hello, 

Can you provide me some screenshot please and the connector that you use ? 
I've can't really understand the issue right now :smile: 

Thanks

**Comment by pmpetit** [comment]
![image](https://user-images.githubusercontent.com/4059185/72053649-c0a2d900-32c7-11ea-989c-0bbc8727decf.png)

in this page 
![image](https://user-images.githubusercontent.com/4059185/72053718-db754d80-32c7-11ea-8065-9e7576279087.png)
thereis no schema_registry_url info

when i udpate, then, in the json the fields  youy can see that informations about schema_registry url are not there any more:
![image](https://user-images.githubusercontent.com/4059185/72053917-46bf1f80-32c8-11ea-9b1e-dee5ccea2a23.png)

**Comment by pmpetit** [comment]
i talk about  : key.converter.schema.registry.url

**Comment by tchiotludo** [comment]
Ok thanks !
I've all the infos to reproduce now !

**Comment by tchiotludo** [comment]
I've added some hardcoded configuration but seems to be weird, can you try on dev image
