### ISSUE TITLE
Broken Travis Build

### ISSUE THREAD

**Issue by hoeggi** [tchiotludo/kafkahq#180]
The update to Kafka 2.4 in commit https://github.com/tchiotludo/kafkahq/commit/a6ebf24f8c0ac2936397361aaf4ff4d3d4f706c4 
broke travis builds because of failing tests.

The reason for this is this commit in kafka https://github.com/apache/kafka/pull/6948
that removes ZkUtils. 
io.confluent.kafka.schemaregistry.rest.SchemaRegistryConfig has a dependency on that class, so the tests fail with a NoClassDefFound. 

I'm unable to build the project itself, so i can't verify if it also breaks the project at runtime or only fails in tests.

**Comment by tchiotludo** [comment]
Hello, 
I know, the last version of Kafka break only the unit test that depend on Confluent Schema Registry Server.
I don't think it break the Runtime of KafkaHQ.
To be honest, I need this new version, there is a regression on Kafka 2.3.* that lead to timeout for some users (works on 2.2 & 2.4 but not on 2.3). 
I know that confluent will very soon release a new version of Confluent Schema Registry Server, and to be honest I wait for the release to release a new version of KafkaHQ.
IMO, If you need to build it manually, just downgrade for now to kafka 2.3 on `build.gradle`. 
Hope the release to be in few day and not weeks to release a new version :crossed_fingers:

**Comment by parmarques** [comment]
Hi,
Confluent released the version 5.4.0 for kafka 2.4. 
[https://docs.confluent.io/current/release-notes/index.html](url)

**Comment by tchiotludo** [comment]
fix in 4f4c96a1e2c010bf5fc1dbcd85bfebce5396c177
