### ISSUE TITLE
UI Questions

### ISSUE THREAD

**Issue by jessetandor** [tchiotludo/kafkahq#182]
Hi, just some simple UI questions i couldn't get from the readme, nothing complicated:

What is the value in the top right corner? It changes pages with left/right but the value presented is something else - can we have it simply display the current page number?

Example: https://imgur.com/a/i3tLDcK

As far as i can see - there is no on the fly sorting for columns in the Topic section? It has to be configured in the config file and then applied - any future plans to include it?

Thanks :)

**Comment by tchiotludo** [comment]
Hello, 

The number is the total number of topics without pagination.
I prefer the total number of elements instead of current page, it will be nice to have current page also displayed.

The sort on topic is already requested #147, PR are welcome on this !
