### ISSUE TITLE
Which ACLs does KafkaHQ need?

### ISSUE THREAD

**Issue by crunchtime-ali** [tchiotludo/kafkahq#185]
Which ACLs does KafkaHQ require for its Kafka-access? I don't want to run it with superuser.

**Comment by tchiotludo** [comment]
I never play with ACL a lot & depending on usage you want to have for KafkaHQ 

If you want a read only, this one may be sufficient : 
- DESCRIBE 
- DESCRIBE_CONFIGS
- READ | Group | OffsetFetch
- READ | Topic | Fetch


To interact with the offset you will need : 
READ | Group | OffsetCommit
READ | Topic | OffsetCommit

If you want to do more : 
- CREATE
- DELETE 
- ALTER | Cluster | CreateAcls
- ALTER | Cluster | DeleteAcls
- ALTER_CONFIGS | Cluster | AlterConfigs
- ALTER_CONFIGS | Topic | AlterConfigs

If you have some goof feedback on this, a PR on README will be really appreciate :+1:

**Comment by jessetandor** [comment]
I tried to give it read only access (read and describe) and this was not working in an older version. Perhaps it's ok now..

**Comment by tchiotludo** [comment]
let me know if you need more help
