### ISSUE TITLE
Getting Prometheus Metrics NaN

### ISSUE THREAD

**Issue by bonkilla** [tchiotludo/kafkahq#195]
After configure it with a test server (SASL_PLAINTEXT) + Kerberos configuration we are able to get the prometheus metrics (cool) but still some of them showing like NaN.

I'm runing it as a jar file with java 13.

Thanks!

**Comment by tchiotludo** [comment]
I think the NAN is coming from kafka consumer ? right ? 

Another things : can you help this guy about Keberos : https://github.com/tchiotludo/kafkahq/issues/194 please ? 
I don't have a cluster to help him :)
Thanks

**Comment by vthorwat** [comment]
Hello @bonkilla ,


Can you please show us the application.yml that you have configured in your enviroment.

Note : We are actually want to verify out configuration is right or not. You can replcae your domain & principal name redacted.

Your help is appreciated...! 👍

**Comment by vthorwat** [comment]
Hello @bonkilla  ,

Currently we have updated our application.yml with below changes please let us know if something missed out.

kafkahq:
clients-defaults:
consumer:
properties:
default.api.timeout.ms: 60000
connections:
jbdl-dev:
properties:
bootstrap.servers: "BROKER:6667,BROKER:6667,BROKER:6667"
security.protocol: SASL_PLAINTEXT
#sasl.enabled.mechanisms: GSSAPI
sasl.kerberos.service.name: kafka
sasl.jaas.config: com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/etc/security/keytabs/kafka.service.keytab" principal="kafka/HOSTNAME@REALM.COM";

security:
default-groups: # Default groups for all the user even unlogged user

admin
groups:
admin: # Group name
roles: # roles for the group

topic/read
topic/insert
topic/delete
topic/config/update
node/read
node/config/update
topic/data/read
topic/data/insert
topic/data/delete
group/read
group/delete
group/offsets/update
registry/read
registry/insert
registry/update
registry/delete
registry/version/delete
acls/read
connect/read
connect/insert
connect/update
connect/delete
connect/state/update
topic-reader: # Other group
roles:

topic/read
basic-auth:
user: admin # Username
password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918 # Password in sha256
groups: # Groups for the user

admin
topic-reader
micronaut:
server:
port: 7070
endpoints:
env:
enabled: true
sensitive: false

We are facing below error : 
![kafkaHQ_issue2](https://user-images.githubusercontent.com/14247410/72888726-1f3e6d00-3d34-11ea-890d-e519f1cc7d31.PNG)
![kafkaHQ_issue3](https://user-images.githubusercontent.com/14247410/72888728-1fd70380-3d34-11ea-9f5e-94c124329145.PNG)

**Comment by bonkilla** [comment]
@vthorwat let me take a look my app.yml and I will get back to you with any help ( I wish)

@tchiotludo I think the NAN is coming from kafka consumer ?  Yes you are right. We would like to have offset and lag metrics from every topic/partition.

Regards

**Comment by tchiotludo** [comment]
@bonkilla : It's not the case for consumer, it will only track internal consumer for KafkaHQ, not the one for the cluster. 
I don't think that KafkaHQ will report this kind of metrics, I would suggest to use a more suitable way to export metrics : https://github.com/danielqsj/kafka_exporter
KafkaHQ is a java app, not really light weight and not really suitable to export metrics.

**Comment by bonkilla** [comment]
@tchiotludo thanks for the info. I was totally wrong.
@vthorwat check this:


server:
    base-path: "" # if behind a reverse proxy, path to kafkahq without trailing slash (optional). Example: kafkahq is
                  # behind a reverse proxy with url http://my-server/kafkahq, set base-path: "/kafkahq".
                  # Not needed if you're behind a reverse proxy with subdomain http://kafkahq.my-server/
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.kafkahq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {} {}] [Status: {}] [Ip: {}] [Length: {}] [Port: {}]" # Logger format

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed
        #sasl.jaas.config: com.sun.security.auth.module.Krb5LoginModule required        useKeyTab=true storeKey=true  keyTab="/home/martinezdavi01/ageapdsk-mirror-eaas-ins101.keytab"  principal="eaasins/ageapdsk-mirro
r-eaas-ins101.prod.hnd2.bdd.local@KAFKA200.GEAP.RAKUTEN.COM"
        #sasl.jaas.config: "/home/martinezdavi01/kafka_server_jaas.conf"
  # list of kafka cluster available for kafkahq
  connections:
    test_cluster: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "SERVER:9092"
        security.protocol: "SASL_PLAINTEXT"
        authorizer.class.name: kafka.security.auth.SimpleAclAuthorizer        
        sasl.jaas.config: com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="keytab path file" principal="principal used";
        sasl.kerberos.service.name: servicename (must be the same than the server!)


and when I run the jar important to add the kerberos conf with the java.security.krb5.conf parameter as this

sudo jdk-13/bin/java -Djava.security.krb5.conf=krb5.conf -Dmicronaut.config.files=application_dmd.yml -jar kafkahq.jar

Please let me know if it worked for you. If you need anything else let me know,

**Comment by vthorwat** [comment]
Thanks @bonkilla  for this information . 

I'll try this in my environment & let you know

**Comment by vthorwat** [comment]
Hello @bonkilla 

Thanks, for your help, We are able to Start the KafkaHq

I am able to see the topic list with below configurations:
kafkahq:
connections:
bdl-dev:
properties:
bootstrap.servers: "BROKER:6667,BROKER:6667,BROKER:6667"
security.protocol: SASL_PLAINTEXT
sasl.kerberos.service.name: kafka
sasl.jaas.config: com.sun.security.auth.module.Krb5LoginModule required useTicketCache=true useKeyTab=true keyTab="/etc/security/keytabs/kafka.service.keytab" principal="PRINCIPAL@REALM.COM";

But When I am adding this below Property in app.yml it is giving WARNING as Is is not known config:

Property:
authorizer.class.name: kafka.security.auth.SimpleAclAuthorizer

Error:
2020-01-23 14:43:14,214 WARN pGroup-1-8 o.a.k.c.c.ConsumerConfig The configuration 'authorizer.class.name' was supplied but isn't a known config.

**Comment by tchiotludo** [comment]
Closing since it was a misunderstanding !

**Comment by bonkilla** [comment]
I couldn't make work the ACL setting. Let me know if you are able to see it.

Having said this, are using any tool to monitor offset and lag that works with kerberos?

**Comment by tchiotludo** [comment]
personally, I don't have any cluster with kerberos, so never tried ... sorry can't help here !
