### ISSUE TITLE
missing -jar parameter in Java runtime startup in README.md

### ISSUE THREAD

**Issue by Lars-Wunderlich** [tchiotludo/kafkahq#2]
The "-jar" parameter is missing while trying to start up the application manually.
It must be "java -jar kafkahq.jar prod" instead of "java kafkahq.jar prod"
And by the way, it also runs successfully in Java 10.0, not only Java 8.

**Comment by tchiotludo** [comment]
I'll correct the `README.md` and also include the min version of java.
For the java 8 version, I'm quite surprise since the docker image is based on java8 : `https://github.com/tchiotludo/kafkahq/blob/master/Dockerfile`. 
Can you paste the error please ?
