### ISSUE TITLE
trying to create a new schema 

### ISSUE THREAD

**Issue by Yggdrassil80** [tchiotludo/kafkahq#210]
Hi,

First of all, thx for this application, its really usefull.

I have a problem that seems a bug when i try to create a new schema using "Schema Registry" option of left menu.

I have many schemas created automatically but when i push  "Create a Subject" button, the form that appear is disabled and seems that hq understand that i'm trying to update a schema instead of create one.

I'm sure that i have all rights because im using a superuser to connect.

Searching a little into the code i found this in schema.ftl file:

```
...
<#macro form config schema>
    <#-- @ftlvariable name="schema" type="org.kafkahq.models.Schema" -->
    <#-- @ftlvariable name="config" type="org.kafkahq.models.Schema.Config" -->
    <#assign canUpdate=(schema?has_content && roles?seq_contains("registry/update") == true) || roles?seq_contains("registry/insert") == true>
    <form enctype="multipart/form-data" method="post" class="khq-form khq-form-config">
        <fieldset ${(!canUpdate)?then("disabled=\"disabled\"", "")}>
...
```
I check this code into the navigator using web developer tools too.

I suspect that "schema?has_content" it's returning false but i dont know how is this possible.

Someone can reproduce this behaviour ?

regards!

**Comment by tchiotludo** [comment]
Hi, 

Thanks for your report. 
To be honest, I try on my side and I just can't reproduce the issue.
`schema?has_content` can't be set on the page create so really don't understand.
Can you send me the url of the page where you see the disabled button please ?

**Comment by Yggdrassil80** [comment]
Hi! Really sorry, was a bug that i found in 0.10.0. In a 0.12.0 it works.

Seems that in 0.10.0 in schema.ftl there are two roles defined with a old definition (schema/update and schema/insert) when the correct roles must be registry/update and registry/insert.

I correct this in my installation addign this two old roles and i deletem them when i update to last version.

Regards and thxs for answer.

**Comment by tchiotludo** [comment]
ok :) 
Glad to know it woks!
