### ISSUE TITLE
Creation of ErrorController fails - endless loop

### ISSUE THREAD

**Issue by geertvb** [tchiotludo/kafkahq#212]
Creation of ErrorController fails because there are multiple candidates for viewsRenderer.
As a result the application goes into an endless loop.

Error found when enabling the debug log:
```
Message: Multiple possible bean candidates found: 
[io.micronaut.views.soy.SoySauceViewsRenderer, 
io.micronaut.views.freemarker.FreemarkerViewsRenderer, 
io.micronaut.views.soy.SoyTofuViewsRenderer]
Path Taken: new ErrorController([ViewsRenderer viewsRenderer],RequestHelper requestHelper)]:  
java.lang.Throwable -> ErrorController#HttpResponse error(HttpRequest request,Throwable e)
```

Workaround:
The soy view controllers can be disabled in the application.yml
```
micronaut:
  views:
    soy:
      enabled: false
```

**Comment by tchiotludo** [comment]
Thanks for the investigation ! 
I will look at further and I think I will remove all template engine that I'm not using to avoid conflict and dependencies overhead 
relate to #209

**Comment by tchiotludo** [comment]
Fix on last `dev` version, thanks for your help
