### ISSUE TITLE
ability to order the table columns

### ISSUE THREAD

**Issue by BDeus** [tchiotludo/kafkahq#213]
Hi,
first of all thank you @tchiotludo for your great job. I searched for a replacement for KafkaManager and kafkahq is a great open source tool.
I'm asking about the possibility to sort the topic by size/numbers of events, etc... in the UI.
Is it something easily doable ?

**Comment by tchiotludo** [comment]
Hi,
Thanks for your support !! Glad to know that you are happy with KafkaHQ.

For the features, it's not possible directly with the Kafka API.
The only way to go further will be have an internal database replicating data from Kafka cluster.

I'm not really sure to do that one day.

**Comment by BDeus** [comment]
I don't get it. Can't the sort be done in the controler part ?
I don't think you paginate the topics by the Kafka API. It has to be done by the kafkahq code.
Can the topics sort be done by the TopicController ?

**Comment by tchiotludo** [comment]
There is pagination on TopicControler because all the data is really time consuming (specially consumer group, size, ...) operation. 

We have user with thousand of topics, so we just can't fetch all the topic data.
