### ISSUE TITLE
How to disable Authentication. 

### ISSUE THREAD

**Issue by JinnaBalu** [tchiotludo/kafkahq#214]
I have tried with 

```yml
kafkahq:
          security:
            enabled: false
```

**Comment by tchiotludo** [comment]
Hello, 

Look at here : https://github.com/tchiotludo/kafkahq/blob/dev/src/main/resources/application.yml

Must be `micronaut:` and take care of indentation.

**Comment by tchiotludo** [comment]
closing it as they is no response, reopen if needed
