### ISSUE TITLE
Issue with ldap groups and special characters

### ISSUE THREAD

**Issue by vanveele** [tchiotludo/kafkahq#215]
I could be wrong, but it seems that micronaut does some configuration property normalization which is causing an issue with some of my configured ldap groups in kafkahq.
What I have found so far.
- groups which are written 'CamelCase' are converted to 'camel-case'; not a show stopper since kafkahq lowercases the groups for matching, so I could use 'camelcase'
- groups with spaces, eg 'Security Group A', is converted to 'security-group-a'
- groups with periods are truncated, eg  'group@teamname.region', is converted to 'group@teamname'

Should the kafkahq.security.ldap.groups section be adjusted to set the LDAP group name as an value rather than a property?

**Comment by vanveele** [comment]
This is the behaviour I see: 
https://github.com/micronaut-projects/micronaut-core/blob/master/src/main/docs/guide/config/propertySource.adoc#property-value-binding

**Comment by vanveele** [comment]
Parameter getting used as name here: https://github.com/tchiotludo/kafkahq/blob/dev/src/main/java/org/kafkahq/configs/LdapGroup.java#L16

**Comment by tchiotludo** [comment]
Yes you can pass the special characters name as property `name:`.
I don't have the time to document these but there is another issue on the same subject : https://github.com/tchiotludo/kafkahq/issues/178

**Comment by vanveele** [comment]
brilliant. thanks for the explaining. I knew I must be doing something wrong.

**Comment by tchiotludo** [comment]
added some doc on readme
