### ISSUE TITLE
error on topic

### ISSUE THREAD

**Issue by pmpetit** [tchiotludo/kafkahq#220]
Hello, i am using kafkaconnect from aiven and i face this error :

![image](https://user-images.githubusercontent.com/4059185/74457586-c2445b80-4e88-11ea-8e53-1cc2d1a463b9.png)

Did you have ever seen such a case ?

Thanks
ps : my version is 0.12

**Comment by pmpetit** [comment]
already seen

**Comment by tchiotludo** [comment]
Do you have some context ?
This error must be very rare and transient due to broker unbalanced.
Is this error disappear ?

**Comment by pmpetit** [comment]
Hello,
the context is : kafkaconnect at aiven, kafka @ aiven, i removed all existing topics through the aiven web console
then now it does not work any more.
It is still the case now.

**Comment by pmpetit** [comment]
it looks like issue #216

**Comment by tchiotludo** [comment]
Ok thanks for sharing !!
Seems that Kafka don't cleanup metadata from consumer group when the topic is deleted 🤨
I think I could catch this use case for consumer group.
