### ISSUE TITLE
Using micronaut LDAP authentication with sAMAccountName

### ISSUE THREAD

**Issue by hdjur** [tchiotludo/kafkahq#235]
Hi, 

I am constantly getting "User not found" when trying to authenticate with AD, tried to use both ports 389 or 3268, the result is same. But I don't know how to specify user search filter for sAMAccountName. Is it possible with micronaut at all, and if so, could you provide an example of configuration?

**Comment by hdjur** [comment]
It is possible, like this:
micronaut.security.ldap.*.search.filter: "sAMAccountName={0}"

https://micronaut-projects.github.io/micronaut-security/latest/guide/#io.micronaut.configuration.security.ldap.configuration.LdapConfiguration$SearchConfiguration

**Comment by tchiotludo** [comment]
:+1:
