### ISSUE TITLE
Read-Only Mode

### ISSUE THREAD

**Issue by cg83** [tchiotludo/kafkahq#25]
Hi there

Thanks for this wonderful application, it's a fantastic start for only a few months old :)

Would there be an option to allow a read-only mode please? This would allow our testing team to have read ability without the accidental option to change/edit/delete.

Thanks very much indeed.

**Comment by tchiotludo** [comment]
Hello @cg83,

Thanks for the good feedback !

Sound a good idea, I haven't decided how to handle ACL for now. 
A read-only could be a good start before full ACL.

Keep it in road map 👍

**Comment by tchiotludo** [comment]
Just release [0.5.0](https://github.com/tchiotludo/kafkahq/releases/tag/0.5.0) with ACL and also **read only mode** !
