### ISSUE TITLE
Default Sort Order

### ISSUE THREAD

**Issue by cg83** [tchiotludo/kafkahq#28]
Hi Again :)

We've tried changing the default sort order from "Oldest" to "Newest" in the code and updated the tests, but it still defaults to Oldest when viewing topics.

What would be the best way to get a "Newest" sort order available please?

Thanks very much indeed!
cg

**Comment by cg83** [comment]
As a workaround for now, in topicsList.ftl we've added;

adding " ?sort=NEWEST " to line 73;

                            <a href="${basePath}/${clusterId}/topic/${topic.getName()}?sort=NEWEST" ><i class="fa fa-search"></i></a>

Thanks again for this great software 👍

**Comment by tchiotludo** [comment]
The reason that the default sort in OLDEST is because NEWEST is slower than OLDEST.
NEWEST fetch partition per partition, OLDEST can fetch all partition in 1 fetch.

There isn't any solutions for now, but, i will put a configuration options in a future release !
