### ISSUE TITLE
Toggle to show/hide internal topics

### ISSUE THREAD

**Issue by zthulj** [tchiotludo/kafkahq#30]
Hi,

Could be interesting to be able to hide internal topics as we don't always need to see them.

**Comment by tchiotludo** [comment]
You want a toggle on ui or a configuration parameters to hide them globally ?

**Comment by zthulj** [comment]
IMO a toggle on ui would be cool and more practical

**Comment by tchiotludo** [comment]
ok will do both of them, thanks for feedback
