### ISSUE TITLE
Topic browser doesn't display XML messages correctly after upgrade from 0.2.1 to 0.4.1

### ISSUE THREAD

**Issue by rkettelerij** [tchiotludo/kafkahq#34]
We have a topic that contains XML messages. With KafkaHQ 0.2.1 these messages are displayed correctly, it includes even syntax highlighting. After upgrading to KafkaHQ 0.4.1 the XML messages aren't displayed correctly anymore: Only the values between the XML tags are visible, the XML tags itself are removed. Downgrading to 0.2.1 resolved the issue.

I suspect this is due to the upgrade to Micronaut and probably some HTML/XML-escaping setting that that must be turned off.

**Comment by tchiotludo** [comment]
ok got it, I will fix it asap

**Comment by tchiotludo** [comment]
fix in last release, thanks for the report !!

**Comment by rkettelerij** [comment]
Thanks! That was fast 👍 Just installed the new release and the XML messages are now displayed correctly.
