### ISSUE TITLE
Impossible to logout after login.

### ISSUE THREAD

**Issue by rsegura** [tchiotludo/kafkahq#42]
Would be nice add a button to login/logout in the web

**Comment by tchiotludo** [comment]
I've try but I have some trouble with micronaut about this feature.
Will add it in a future release

**Comment by tchiotludo** [comment]
There is still the issue from micronaut I think : https://github.com/micronaut-projects/micronaut-core/issues/1532

Wait for the response, but the logout button is available on `dev` image with `docker pull tchiotludo/kafkahq:dev`
