### ISSUE TITLE
Setting base-path breaks KafkaHQ

### ISSUE THREAD

**Issue by joekohlsdorf** [tchiotludo/kafkahq#44]
I am running behind a reverse proxy so I put the following into my config as documented:
```
    kafkahq:
      server:
        base-path: "https://kafkahq.example.com"
```

When opening KafkaHQ I get redirected to the login page and CSS/JS doesn't load (401 Unauthorized). I haven't setup any users so I shouldn't get redirected to the login page.

I removed `base-path` from my config and everything started working fine, even behind the proxy. I suggest to simply remove this instruction from the documentation.

**Comment by tchiotludo** [comment]
added this to be more explicit about this configuration variable :  
```yaml
    base-path: "" # if behind a reverse proxy, path to kafkahq with trailing slash (optionnal). Example: kafkahq is
                  # behind a reverse proxy with url http://my-server/kafkahq, set base-path: "/kafkahq/".
                  # Not needed if you're behind a reverse proxy with subdomain http://kafkahq.my-server/
```
