### ISSUE TITLE
Can't inspect topics with Snappy compressed messages

### ISSUE THREAD

**Issue by joekohlsdorf** [tchiotludo/kafkahq#45]
I have topics which have messages which are compressed with Snappy.

When trying to inspect these topics I get the following Exception:
```
java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.7-a96d7c8e-ec5a-466f-8586-be0f29616ce5-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.7-a96d7c8e-ec5a-466f-8586-be0f29616ce5-libsnappyjava.so)
```

**Comment by tchiotludo** [comment]
You use the docker image I supposed ?
Or standalone jar ?

Thanks for the report.

**Comment by joekohlsdorf** [comment]
Yes, standard Docker image `tchiotludo/kafkahq:0.5.2`. If I was using standalone I'd just install the missing library :-).

**Comment by tchiotludo** [comment]
available on `dev` image with `docker pull tchiotludo/kafkahq:dev`

**Comment by cg83** [comment]
Hey there - can we get this into the main release images too please?
Thanks very much.
