### ISSUE TITLE
Login redirect does not honor base-path 

### ISSUE THREAD

**Issue by tine2k** [tchiotludo/kafkahq#46]
I use kafkahq with security turned on and have the base-path set to "/kafka-hq".

When I browse to `/kafka-hq` I get redirected to `/login/unauthorized` instead of `/kafka-hq/login/unauthorized`. When using a reverse proxy the path `/login/unauthorized` will  not serve the kafkahq login page because the prefix is missing.

Even browsing to `/kafka-hq/login/unauthorized` will forward `/login/unauthorized`.

**Comment by tchiotludo** [comment]
available on `dev` image with `docker pull tchiotludo/kafkahq:dev`

**Comment by tine2k** [comment]
What a fast fix! Ill give it a try tonight. Thanks!

**Comment by tine2k** [comment]
@tchiotludo I just tried the latest dev docker image: now it constantly redirects to /kafka-hq/login/unauthorized in a loop. Browser eventually stops with "too many redirects". I will have a closer look to why this is tonight.

**Comment by tchiotludo** [comment]
Weird, didn't see it during my test, will have a look also

**Comment by tine2k** [comment]
Seems to be related to my config. I am overwriting the default roles. I will further investigate.
