### ISSUE TITLE
Handle SIGINT

### ISSUE THREAD

**Issue by rdohms** [tchiotludo/kafkahq#5]
First of all, thank you, this is an awesome tool.

I'm running it on demand, so instead of `-d` in docker run we just run it. However if i send a SIGINT it simply does not stop, i need to forcefully `docker stop` it.

Is there anything you can do about this in the code?

**Comment by tchiotludo** [comment]
Thanks for your feedback ! 
Glad to see people using it :smile: 

I just try : 
`docker run -ti  tchiotludo/kafkahq`

After hiting ctrl+c, the server stop gracefully : 
`2019-01-04 10:31:46,435  INFO Thread-1   org.kafkahq.App            Stopped`

How do you send the SIGINT signal ?

**Comment by rdohms** [comment]
Oh boy, please ignore me, I must be hungover from New Years still, i forgot to add the `-ti`.

And yeah, its a pretty handy app to look into kafka quickly, the json parsing is pretty useful.
