### ISSUE TITLE
NPE when header value is null

### ISSUE THREAD

**Issue by cadu-goncalves** [tchiotludo/kafkahq#56]
Found an issue on class **org.kafkahq.models.Record**, if an header has value null a NPE occurs on **line 40**:

```java
    this.headers.put(header.key(), new String(header.value()));
```

Suggestion:

```java
        for (Header header: record.headers()) {
            if(Objects.isNull(header.value())) {
                this.headers.put(header.key(), "");
            } else {
                this.headers.put(header.key(), new String(header.value()));
            }
        }
```

**Comment by tchiotludo** [comment]
I've decided to handled null value on the whole application and displayed a true `null` 
Thanks for the report !

**Comment by cadu-goncalves** [comment]
OK, I've built an image based on `dev` branch, works pretty well. I've just used the Dockerfile from `master` branch in order to get a runnable image.
Thank you!

**Comment by tchiotludo** [comment]
Glad to know it ! 
FYI, normally docker image dev is available : https://hub.docker.com/r/tchiotludo/kafkahq/tags
But I've a test that failed on dev image preventing the build to be done :hourglass:

**Comment by lostiniceland** [comment]
@tchiotludo 
We just moved from KafkaHQ to AKHQ and in the current version the UI filters out any header with a null value.
This is bad for analysis since we just had the case where a null header was wronly published which caused an Exception in the application. Luckily we still had the old version running  where I was able to find the problematic key.
Should I open a new issue for this? Maybe have a config option what should be filtered and what not.

**Comment by tchiotludo** [comment]
@lostiniceland can you provide a screenshot please ?
I don't understand exactly the issue

**Comment by lostiniceland** [comment]
KafkaHQ 0.11
![grafik](https://user-images.githubusercontent.com/1516116/184309946-93037b1b-c6f4-474d-b4bb-6657918dff1a.png)

AKHA 0.21
![grafik](https://user-images.githubusercontent.com/1516116/184310027-8f6697c2-7c1a-4393-a5bc-615a4ba33548.png)

Both views show the same message (highlighted by uuid). Offset is 18.
While KafkaHq shows 19 headers including the one with null AKHQ 0.21 only shows 18 header.

**Comment by tchiotludo** [comment]
@lostiniceland : please create a new issue please
