### ISSUE TITLE
Lower right buttons in the UI are illisible

### ISSUE THREAD

**Issue by ftardif** [tchiotludo/kafkahq#58]
![image](https://user-images.githubusercontent.com/221462/57636701-a0bfe780-7577-11e9-8f1a-af369a696fb0.png)

**Comment by tchiotludo** [comment]
What is the browser and the os please ?

Seems weird standard bootstrap here

**Comment by ftardif** [comment]
Google Chrome is up to date
Version 74.0.3729.131 (Official Build) (64-bit)

does the same on my collegues computers. And I have the same with safari

**Comment by tchiotludo** [comment]
Forgot to ask the KafkaHQ version ?
On a old version, I've the bug as I remember

**Comment by ftardif** [comment]
cda2f894fa5f        tchiotludo/kafkahq:0.7.0                  "docker-entrypoint.s…"   4 hours ago         Up 3 hours          0.0.0.0:9001->8080/tcp   kafkahq

**Comment by tchiotludo** [comment]
last version, really can't reproduce ... 
Try on several brower, but always blue.

Maybe, if  you do not mind,  on chrome on the button, click right, inspect.
And attach a screenshot off dev tools with styles tabs, and another one with computed may help me to understand ...

**Comment by ftardif** [comment]
![image](https://user-images.githubusercontent.com/221462/57734801-ced52280-7670-11e9-9c9a-02f0b76b119a.png)


and BTW, your tool is great! 👍  
The ability to get all the CLI functions under a same webapp was definitely lacking in the kafka!

**Comment by tchiotludo** [comment]
Thanks for the BTW :+1: 

Screenshot doesn't help, you have the right css classes ... Seems really weird.

Maybe a screenshot with the right panel complete (with border: 0px and so on) and the also the tab in the panel with title `computed` may help ? 

Sorry to bother but really can't understand

**Comment by ftardif** [comment]
![image](https://user-images.githubusercontent.com/221462/57854873-43b27480-77b7-11e9-8c7f-fb9188440f05.png)

**Comment by ftardif** [comment]
![image](https://user-images.githubusercontent.com/221462/57854922-693f7e00-77b7-11e9-8e96-86cbbc594f58.png)

**Comment by ftardif** [comment]
and I tried it by running your docker-compose locally on my laptop and accessing the page trough local host and I got the same "white button" behavior.

**Comment by tchiotludo** [comment]
really weird ... 

here is mine : 
![image](https://user-images.githubusercontent.com/2064609/57855721-a32a7780-77eb-11e9-95d7-4bb23a0f1d4d.png)

There is a lot of css property missing on your side... 
Can you try in incognito mode please ? (I see that you have a lot of extension)

**Comment by ftardif** [comment]
same in incognito mode, and same on safari

**Comment by tchiotludo** [comment]
don't have any error on network tabs ?

**Comment by ftardif** [comment]
![image](https://user-images.githubusercontent.com/221462/57856241-98a3ba00-77ba-11e9-8403-70ad80fc5547.png)

**Comment by tchiotludo** [comment]
exactly the same than mine ... 

Really stuck here for now, can't find any reason ... 
Will poke you if I have any idea, but I think I've done all the thing I can do remote ...

**Comment by SimonGourdeau** [comment]
The problem seem to originate from the  `-webkit-appearance` property defined in `_reboot.scss`.
![Screen Shot 2019-05-16 at 11 51 14 AM](https://user-images.githubusercontent.com/3361686/57868678-6d789500-77d1-11e9-9453-c72bb1a44014.png)
![image](https://user-images.githubusercontent.com/3361686/57868340-ceec3400-77d0-11e9-9a73-385e4cef7ec0.png)

**Comment by tchiotludo** [comment]
really strange, it a simple button from bootstrap 4.

```css
// 1. Prevent a WebKit bug where (2) destroys native `audio` and `video`
//    controls in Android 4.
// 2. Correct the inability to style clickable types in iOS and Safari.
button,
[type="button"], // 1
[type="reset"],
[type="submit"] {
  -webkit-appearance: button; // 2
}
```

Does you have trouble here : https://getbootstrap.com/docs/4.0/components/buttons/ ?

**Comment by SimonGourdeau** [comment]
That's weird, I so see that the `-webkit-appearance: button` applies for the buttons on the bootstrap website, but they are rendered as intended

**Comment by SimonGourdeau** [comment]
I'll look further into this

**Comment by SimonGourdeau** [comment]
It's because the the `btn` css class is used on a `<a>` tag. I get the same quirk when I copy the html from KafkaHQ to the bootstrap website.
![Screen Shot 2019-05-16 at 1 13 32 PM](https://user-images.githubusercontent.com/3361686/57873566-95212a80-77dc-11e9-83e9-f4bb1b86630f.png)

**Comment by tchiotludo** [comment]
So you must have the same broken link just below ? 
https://getbootstrap.com/docs/4.0/components/buttons/#button-tags

There is a <a>

**Comment by SimonGourdeau** [comment]
You are right, the `btn` classes can be used on a `<a>` element. It's a weird interaction between the attribute `type="submit"`, the bootstrap css and the nature of the html element. Is there a reason to prefer a link element over a button? :)

**Comment by tchiotludo** [comment]
Good point, the type submit is completely useless !! 
If you remove this attr on KafkaHQ, is this working correctly ?

It's a simple link not a submit 😀

**Comment by tchiotludo** [comment]
Just publish on new `dev` version
If you can use this image : `docker pull tchiotludo/kafkahq:dev` to see if it correct your issue ?

**Comment by SimonGourdeau** [comment]
Looks good tchiotludo! 👍 Thanks!

**Comment by tchiotludo** [comment]
Glad to hear it !! 
Thanks for your time finding the bug !
