### ISSUE TITLE
Problem with 0.7.0

### ISSUE THREAD

**Issue by xs005** [tchiotludo/kafkahq#59]
I tried the latest one and got the error, but 0.6.0 works well.

**Unrecognized VM option 'PrintGCDateStamps'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.**

**Comment by tchiotludo** [comment]
Thanks for report, fix in https://github.com/tchiotludo/kafkahq/releases/tag/0.7.1
