### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by anto59** [tchiotludo/kafkahq#60]
Version 0.7.1

Error message when I try to login 
More than 1 route matched the incoming request. The following routes matched /login: GET - /login, GET - /login

**Comment by tchiotludo** [comment]
Micronaut have a breaking change between 1.1.1-SNAPSHOT abd 1.1.1 that I can't understand but I was able to workaround
Build in progress for a new release

Thanks for the report

**Comment by anto59** [comment]
Thank you for the fix
