### ISSUE TITLE
Show version

### ISSUE THREAD

**Issue by GuillaumeWaignier** [tchiotludo/kafkahq#81]
It would be useful to display the version somewhere in the IHM (perhaps in a corner).
If we don't use docker, there is no information about the deployed version.
Great product !

**Comment by tchiotludo** [comment]
Thanks ! 

Will add try to find a way to deal with it ! 
For now, you can have the information in json on  `http://localhost:8080/info`

**Comment by GuillaumeWaignier** [comment]
Thanks, the  `tags`  information from the API is perfect.
